# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Connect to CrossLink
#' @description Establishes a connection to the CrossLink backend.
#' @param db_path Path to the DuckDB database file. Defaults to "crosslink.duckdb".
#' @param debug Enable debug logging. Defaults to FALSE.
#' @return An external pointer (XPtr) to the CrossLink connection object.
#' @export
crosslink_connect <- function(db_path = "crosslink.duckdb", debug = FALSE) {
    .Call(`_CrossLink_crosslink_connect`, db_path, debug)
}

#' @title Push Data
#' @export
crosslink_push <- function(cl_ptr, arrow_table, name = "", description = "") {
    .Call(`_CrossLink_crosslink_push`, cl_ptr, arrow_table, name, description)
}

#' @title Pull Data
#' @export
crosslink_pull <- function(cl_ptr, identifier) {
    .Call(`_CrossLink_crosslink_pull`, cl_ptr, identifier)
}

#' @title Query Data
#' @export
crosslink_query <- function(cl_ptr, sql) {
    .Call(`_CrossLink_crosslink_query`, cl_ptr, sql)
}

#' @title List Datasets
#' @export
crosslink_list_datasets <- function(cl_ptr) {
    .Call(`_CrossLink_crosslink_list_datasets`, cl_ptr)
}

#' @title Push Stream Start
#' @export
crosslink_push_stream <- function(cl_ptr, schema, name = "") {
    .Call(`_CrossLink_crosslink_push_stream`, cl_ptr, schema, name)
}

#' @title Pull Stream Start
#' @export
crosslink_pull_stream <- function(cl_ptr, stream_id) {
    .Call(`_CrossLink_crosslink_pull_stream`, cl_ptr, stream_id)
}

#' @title Stream Writer Write Batch
#' @export
crosslink_stream_writer_write_batch <- function(writer_ptr, batch) {
    invisible(.Call(`_CrossLink_crosslink_stream_writer_write_batch`, writer_ptr, batch))
}

#' @title Stream Writer Close
#' @export
crosslink_stream_writer_close <- function(writer_ptr) {
    invisible(.Call(`_CrossLink_crosslink_stream_writer_close`, writer_ptr))
}

#' @title Stream Writer Get Schema
#' @export
crosslink_stream_writer_schema <- function(writer_ptr) {
    .Call(`_CrossLink_crosslink_stream_writer_schema`, writer_ptr)
}

#' @title Stream Writer Get ID
#' @export
crosslink_stream_writer_id <- function(writer_ptr) {
    .Call(`_CrossLink_crosslink_stream_writer_id`, writer_ptr)
}

#' @title Stream Reader Read Next Batch
#' @export
crosslink_stream_reader_read_next_batch <- function(reader_ptr) {
    .Call(`_CrossLink_crosslink_stream_reader_read_next_batch`, reader_ptr)
}

#' @title Stream Reader Close
#' @export
crosslink_stream_reader_close <- function(reader_ptr) {
    invisible(.Call(`_CrossLink_crosslink_stream_reader_close`, reader_ptr))
}

#' @title Stream Reader Get Schema
#' @export
crosslink_stream_reader_schema <- function(reader_ptr) {
    .Call(`_CrossLink_crosslink_stream_reader_schema`, reader_ptr)
}

#' @title Stream Reader Get ID
#' @export
crosslink_stream_reader_id <- function(reader_ptr) {
    .Call(`_CrossLink_crosslink_stream_reader_id`, reader_ptr)
}

#' @title Register Notification Callback
#' @export
crosslink_register_notification <- function(cl_ptr, callback) {
    .Call(`_CrossLink_crosslink_register_notification`, cl_ptr, callback)
}

#' @title Unregister Notification Callback
#' @export
crosslink_unregister_notification <- function(cl_ptr, registration_id) {
    invisible(.Call(`_CrossLink_crosslink_unregister_notification`, cl_ptr, registration_id))
}

#' @title Cleanup CrossLink Connection
#' @export
crosslink_cleanup <- function(cl_ptr) {
    invisible(.Call(`_CrossLink_crosslink_cleanup`, cl_ptr))
}

