name = "DuckConnect"
uuid = "85c7e1c9-1e3d-47f1-8983-f1a28b920ceb"
authors = ["DuckData Team <info@example.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
julia = "1.6"
