name: Simple Data Transformation Pipeline
description: A simple pipeline demonstrating cross-language data processing
db_path: simple_pipeline.duckdb  # Path to CrossLink database
working_dir: ./            # Working directory for scripts

nodes:
  - id: generate_data
    language: python
    script: scripts/generate_data.py
    outputs:
      - raw_data
    params:
      rows: 1000
      
  - id: transform_data
    language: r
    script: scripts/transform_data.R
    inputs:
      - raw_data
    outputs:
      - transformed_data
      

      
  - id: analyze_data
    language: julia
    script: scripts/analyze_data.jl
    inputs:
      - transformed_data
    outputs:
      - analysis_results
      
  - id: create_report
    language: python
    script: scripts/create_report.py
    inputs:
      - transformed_data
      - analysis_results
    outputs:
      - final_report 